import 'prismjs';
import 'prismjs/themes/prism-coy.css';
import './utils/theme';
import './utils/defaultMessages';
import './utils/radioButtons';
import './utils/insertMessage';
import './utils/test';
import '../styles/main.css';
import '../styles/prism.css';
